version: "3.7"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
    - .:/myapp
    ports:
    - "7000:7000"
    extra_hosts:
    - "host.docker.internal:host-gateway"
